name: Do It All

on:
  push:
    branches:
      - "**"

jobs:
  format-and-lint:
    if: contains(github.event.head_commit.message, '[dia]')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prettify all files
        run: npm run format

      - name: Fix linting errors
        run: npm run lint:fix

      - name: Commit and push changes to auto branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: auto/lint
          commit_message: "chore(dia): Auto-format and lint files [skip ci]"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions-bot@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions-bot@users.noreply.github.com>"
          create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(dia): Auto-format and lint files [skip ci]"
          branch: auto/lint
          base: main
          title: "Auto-format & lint fixes"
          body: "This PR applies automatic formatting and lint fixes."
          labels: "auto-lint"
